version: 2.1

orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    working_directory: ~/resz
    # Reuse Docker container specification given by the node Orb
    executor: node/default
    steps:
      - checkout
      # Install the latest npm - the node Orb takes care of it
      - node/install-npm
      # Install dependencies - the node Orb take care of installation and dependency caching
      - node/install-packages:
          app-dir: ~/rest
          cache-path: node_modules
          override-ci-command: npm i
      - run:
          name: Test
          command: npm test
        
workflows:
  test_my_app:
    jobs:
      - test
