--- 
jobs: 
  gql-test: 
    executor: node/default
    steps: 
      - checkout
      - node/install-npm
      - 
        node/install-packages: 
          app-dir: ~/project/gql
          cache-path: node_modules
          override-ci-command: "npm i"
      - 
        run: 
          command: "npm test"
          name: "Test GraphQL"
          working_directory: ~/project/gql
      - 
        discord/status: 
          webhook: "${DISCORD_STATUS_WEBHOOK}"
    working_directory: ~/project
  rest-test: 
    executor: node/default
    steps: 
      - checkout
      - node/install-npm
      - 
        node/install-packages: 
          app-dir: ~/project/rest
          cache-path: node_modules
          override-ci-command: "npm i"
      - 
        run: 
          command: "npm test"
          name: "Test REST"
          working_directory: ~/project/rest
      - 
        discord/status: 
          webhook: "${DISCORD_STATUS_WEBHOOK}"
    working_directory: ~/project
orbs: 
  discord: antonioned/discord@0.1.0
  node: circleci/node@3.0.0
version: 2.1
workflows: 
  catapi-workflow: 
    jobs: 
      - gql-test
      - rest-test
